import React from 'react'
import Head from 'next/head'
import Menu from '../src/components/Menu/Menu'
import styles from '../styles/Home.module.css'
import Users from '../src/components/Users/Users'

export default function Devs() {
    return(
        <div className={styles.container}>
            <Head>
                <title>Devs | Our Devs</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <Menu />
                <Users />
            </main>

        </div>
    )
}