import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Menu from '../src/components/Menu/Menu'
import programador from '../src/assets/images/programador-main.png'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Our Devs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <Menu />
          <div className={styles.section}>
            <div className={styles.col}>
              <h1>O maior banco de devs do Brasil</h1>
              <p>Nao importa se front ou back end, fazer networking e muito importante. Faça parte da maior comunidade de desenvolvedores brasileiros.</p>
            </div>
            <div className={styles.colImage}>
              <Image src={programador}  />
            </div>
          </div>
      </main>
          
    </div>
  )
}
